#!/bin/bash
date=$1
ans=$2
if [ "$ans" -eq "1" ]; then
	#All customer order,OLPN list with PBT and their state
	sudo -u postgres psql -U postgres -d platform_srms -c "copy(select sr.external_service_request_id,sr.state,sr1.external_service_request_id,sr1.state,sr1.received_on,sr1.updated_on,sr1.attributes::json->'pick_before_time' as "PBT" ,sr.attributes::json->'route_id'
 as "RouteId" from service_request sr,service_request_children src, service_request sr1 where sr.id = src.service_request_id and sr1.id = src.servicerequests_id and sr.attributes->>'order_type' = 'CUSTOMER_ORDER' and sr.attributes->>'internal' is null and sr1.attributes->>'internal' is null and to_char(sr.created_on,'YYYY-MM-DD') = '$date') to '/tmp/easy_console.csv'"

elif [ "$ans" -eq "2" ]; then
   	#All OLPN (created+fulfillable) stuck because of unfulfillable
   	#Customer_order,Customer_order_state,OLPN,OLPN_state
	sudo -u postgres psql -U postgres -d platform_srms -c "copy(select sr.external_service_request_id as "Customer_order",sr.state as "Customer_order_state",sr1.external_service_request_id as "OLPN",sr1.state as "OLPN_state" from service_request sr, service_request_children src, service_request sr1 where sr.id = src.service_request_id and sr1.id = src.servicerequests_id and sr.attributes->>'order_type' = 'CUSTOMER_ORDER' and sr.attributes->>'internal' is null and sr1.attributes->>'internal' is null and sr.external_service_request_id in (select sr.external_service_request_id from service_request sr, service_request_children src, service_request sr1 where sr.id = src.service_request_id and sr1.id = src.servicerequests_id and sr.attributes->>'order_type' = 'CUSTOMER_ORDER' and sr.attributes->>'internal' is null and sr1.attributes->>'internal' is null and sr1.external_service_request_id in (select external_service_request_id from service_request where id in (select servicerequests_id from service_request_children where service_request_id in (select id from service_request where type='PICK' and ( (cast (attributes as jsonb)->>'order_type') = 'CUSTOMER_ORDER' ) and ( (cast (attributes as jsonb)->>'internal') is null ) and to_char(created_on,'YYYY-MM-DD') in ('$date') )) and ( (cast (attributes as jsonb)->>'internal') is null ) and state = 'not_fulfillable'))) to '/tmp/easy_console.csv' with CSV"

elif [ "$ans" -eq "3" ]; then
  	#All OLPN status of Put which is not in PROCESSED
	sudo -u postgres psql -U postgres -d platform_srms -c "copy(select sr.external_service_request_id as "Customer_order",sr1.external_service_request_id as "OLPN",sr1.state as "OLPN_state" ,sr.state as "Customer_order_state" from service_request sr, service_request_children src, service_request sr1 where sr.id = src.service_request_id and sr1.id = src.servicerequests_id and sr.attributes->>'order_type' = 'CUSTOMER_ORDER' and sr.attributes->>'internal' is null and sr1.attributes->>'internal' is null and sr.external_service_request_id in (select sr.external_service_request_id from service_request sr, service_request_children src, service_request sr1 where sr.id = src.service_request_id and sr1.id = src.servicerequests_id and sr.attributes->>'order_type' = 'CUSTOMER_ORDER' and sr.attributes->>'internal' is null and sr1.attributes->>'internal' is null and sr1.external_service_request_id in (select abc.external_service_request_id from (select sr.id as parent_id, sr1.id as child_id, sr.external_service_request_id from service_request sr, service_request_children src, service_request sr1 where sr.id = service_request_id and sr1.id = servicerequests_id and sr.attributes->>'internal' is null and sr.external_service_request_id in (select external_service_request_id from service_request where id in (select servicerequests_id from service_request_children where service_request_id in (select id from service_request where type='PICK' and ( (cast (attributes as jsonb)->>'order_type') = 'CUSTOMER_ORDER' ) and ( (cast (attributes as jsonb)->>'internal') is null ) and to_char(created_on,'YYYY-MM-DD') in ('$date') )) and ( (cast (attributes as jsonb)->>'internal') is null ))) abc, stages stages where abc.child_id = order_id and transaction_type = 'UDP Put' and transaction_status != 'PROCESSED')))  to '/tmp/easy_console.csv' with CSV"
elif [ "$ans" -eq "4" ]; then
  	#All OLPN status whether they are in PUT/PACK/CASE_PICK/EACK_PICK
  	sudo -u postgres psql -U postgres -d platform_srms -c "copy(select abc.external_service_request_id, abc.child_id orderline_id, transaction_type, transaction_status from (select sr.id as parent_id, sr1.id as child_id, sr.external_service_request_id from service_request sr, service_request_children src, service_request sr1 where sr.id = service_request_id and sr1.id = servicerequests_id and sr.attributes->>'internal' is null and sr.external_service_request_id in (select external_service_request_id from service_request where id in (select servicerequests_id from service_request_children where service_request_id in (select id from service_request where type='PICK' and ( (cast (attributes as jsonb)->>'order_type') = 'CUSTOMER_ORDER' ) and ( (cast (attributes as jsonb)->>'internal') is null ) and to_char(created_on,'YYYY-MM-DD') in ('$date') )) and ( (cast (attributes as jsonb)->>'internal') is null) and state = 'created')) abc, stages stages where abc.child_id = order_id) to '/tmp/easy_console.csv' with CSV"
	sleep 1
else
	echo "Please chose correct option"
fi


